---
all:
  hosts:
    sonar-01:
      ansible_ssh_user: root
      StrictHostKeyChecking: 'no' 
      # ansible_host: <somehost2>
    nexus-01:
      ansible_ssh_user: root 
      StrictHostKeyChecking: 'no'
      # ansible_host: <somehost>
  children:
    sonarqube:
      hosts:
        sonar-01:
          ansible_ssh_user: root 
          StrictHostKeyChecking: 'no'
    nexus:
      hosts:
        nexus-01:
          ansible_ssh_user: root 
          StrictHostKeyChecking: 'no'
    postgres:
      hosts:
        sonar-01:
          ansible_ssh_user: root 
          StrictHostKeyChecking: 'no'
  vars:
    ansible_connection_type: paramiko
    ansible_user: root
