---
all:
  hosts:
    sonar-01:
      ansible_ssh_user: root 
      # ansible_host: <somehost2>
    nexus-01:
      ansible_ssh_user: root 
      # ansible_host: <somehost>
  children:
    sonarqube:
      hosts:
        sonar-01:
          ansible_ssh_user: root 
    nexus:
      hosts:
        nexus-01:
          ansible_ssh_user: root 
    postgres:
      hosts:
        sonar-01:
          ansible_ssh_user: root 
  vars:
    ansible_connection_type: paramiko
    ansible_user: root